#!/bin/bash
# Design B Quick Command Reference for RTX4070

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Design B GPU Implementation - RTX4070              ║"
echo "║              Quick Command Reference                       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

REPO="/home/crystal/Documents/Thesis/Pixel2MeshPlusPlus"
cd "$REPO"

echo "STEP 1: CHOOSE YOUR ENVIRONMENT"
echo "================================"
echo ""
echo "Option A - DOCKER (Recommended - No system CUDA needed):"
echo "  docker build -f env/gpu/Dockerfile -t p2mpp-gpu:latest ."
echo "  docker run --gpus all -it -v \$(pwd):/workspace p2mpp-gpu:latest bash"
echo "  cd /workspace"
echo ""
echo "Option B - NATIVE PYTHON (If CUDA 11+ installed):"
echo "  pip install -r env/gpu/requirements_gpu.txt"
echo ""
echo "---"
echo ""
echo "STEP 2: BUILD & VERIFY (Both options)"
echo "====================================="
echo ""
echo "One-command setup:"
echo "  bash env/gpu/setup_and_verify.sh"
echo ""
echo "Or step-by-step:"
echo "  bash env/gpu/build_ops.sh        # Compile CUDA ops"
echo "  # Verify GPU is detected"
echo "  nvidia-smi"
echo ""
echo "---"
echo ""
echo "STEP 3: RUN INFERENCE TEST"
echo "=========================="
echo ""
echo "Quick test (5 samples):"
echo "  head -n 5 data/test_list.txt > data/designB_eval_test.txt"
echo "  python test_p2mpp.py --config cfgs/p2mpp.yaml --checkpoint results/refine_p2mpp/models/meshnet.ckpt-10"
echo ""
echo "In another terminal, monitor GPU:"
echo "  watch -n 1 nvidia-smi"
echo ""
echo "---"
echo ""
echo "STEP 4: BENCHMARK (Design A vs B)"
echo "=================================="
echo ""
echo "Run full benchmark (20-30 min):"
echo "  bash env/gpu/benchmark.sh"
echo ""
echo "Check results:"
echo "  cat outputs/designB/benchmark/design_a_times.txt"
echo "  cat outputs/designB/benchmark/design_b_times.txt"
echo ""
echo "---"
echo ""
echo "STEP 5: CREATE REPORT"
echo "===================="
echo ""
echo "All results go to:"
echo "  outputs/designB/benchmark/    (timing data)"
echo "  outputs/designB/logs/         (detailed logs)"
echo ""
echo "Document in:"
echo "  docs/ch4_designB_spec_and_verification.md"
echo ""
echo "---"
echo ""
echo "KEY FILES & LOGS"
echo "==============="
echo ""
echo "Documentation:"
echo "  DESIGN_B_SETUP_COMPLETE.md              (← Start here)"
echo "  env/gpu/QUICKSTART.md                   (Quick reference)"
echo "  docs/designB_gpu_strategy.md            (Technical strategy)"
echo "  docs/designB_implementation_roadmap.md  (Full plan)"
echo ""
echo "Scripts (all executable):"
echo "  env/gpu/setup_and_verify.sh    (Auto setup)"
echo "  env/gpu/build_ops.sh           (Build CUDA ops)"
echo "  env/gpu/benchmark.sh           (A vs B benchmark)"
echo ""
echo "---"
echo ""
echo "TROUBLESHOOTING"
echo "==============="
echo ""
echo "Check build logs:"
echo "  cat outputs/designB/logs/build_log.txt"
echo ""
echo "Check GPU:"
echo "  nvidia-smi"
echo "  nvcc --version"
echo "  python -c \"import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))\""
echo ""
echo "Verify ops load:"
echo "  cd external"
echo "  python -c \"import tensorflow as tf; mod = tf.load_op_library('./tf_nndistance_so.so'); print('✓ Op loaded')\""
echo ""
echo "---"
echo ""
echo "NEXT ACTION: Read DESIGN_B_SETUP_COMPLETE.md"
echo ""
